# Generated by Django 5.1.4 on 2024-12-11 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_api', '0001_initial'),
        ('deliver_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_address', models.CharField(max_length=100)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Provider Preparing'), (1, 'Waiting for Delivery'), (2, 'Delivering'), (3, 'Completed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_api.customer')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver_api.deliver')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_api.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_api.product')),
            ],
            options={
                'unique_together': {('order_id', 'product_id')},
            },
        ),
    ]
