# Generated by Django 5.1.4 on 2024-12-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_id',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='user_id',
            new_name='user',
        ),
    ]
