# Generated by Django 5.1.4 on 2024-12-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_api', '0002_rename_user_id_deliver_user'),
        ('provider_api', '0002_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliver_api.deliver'),
        ),
    ]
