# Generated by Django 5.1.4 on 2024-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_api', '0004_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='provider_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
