# Generated by Django 5.1.4 on 2024-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0003_chatrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='role',
            field=models.CharField(default='user', max_length=10),
            preserve_default=False,
        ),
    ]
